### ISSUE TITLE
Remove 2020 information from the website

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#218]
The workshop is over and we should update the website and remove the information about it so we can leave it online until we announce the date and location for next year (🤞).

### TODO

- [x] remove _"COMMUNITY WORKSHOP // OCT 16, 2020"_ above the main title
- [x] remove _"Instead of a full-fledged EmberFest 2020 conference, we will run a remote Contributor Workshop. Find all the details below!"_ in the first block of text
- [x] remove entire block about the workshop – from the image until list of mentors
- [x] replace _"ABOUT LAST YEAR"_ with _"ABOUT 2019"_
