### ISSUE TITLE
Announce location/venue

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#226]
We're ready to announce the location and venue for this year's conference. That requires updating the header and adding a content section at the bottom of the page with information of the venue. We're **not** adding a section with information on the closing diner venue for now.

### TODO

- [ ] update header graphic
- [ ] add location text in header besides dates
- [ ] add content section for location/venue below _"Past Speakers"_ section with
  - [ ] title & text
  - [ ] venue photo
  - [ ] map

### Resources

* Desktop design: https://app.abstract.com/projects/61319c30-5f7e-11e9-97d1-abba5ef9115e/branches/a3af1a5b-3521-4888-986e-2e2746596644/commits/latest/files/e6b9cd4c-def8-41b2-8b8c-db26164ae2ee/layers/94E31730-3D18-43AC-93F9-1AA7B808A588?collectionId=d42ca52e-6bac-4be7-a4a4-62d6e223dc37&collectionLayerId=e5b09073-7cbe-4c9d-8a1e-4c962c0873bc
* Mobile design: https://app.abstract.com/projects/61319c30-5f7e-11e9-97d1-abba5ef9115e/branches/a3af1a5b-3521-4888-986e-2e2746596644/commits/3307f1533c4b64b1492c8df7a2e43e14f3746a3a/files/e6b9cd4c-def8-41b2-8b8c-db26164ae2ee/layers/BF4B7744-1981-4B11-94FB-02F63B8F616F ( @marhigh this file seems empty? can you clarify?)
* Text & photo for venue: https://3.basecamp.com/4551353/buckets/17581315/todos/3838606747

**Comment by marhigh** [comment]
@marcoow the mobile design for the announced location had not been created yet. You can always refer to the collection on Abstract for the work that is ready to be shared (https://share.goabstract.com/1d4de827-121c-4179-9e6c-5f45c5c547bb). 

I have created the mobile design now, it can be seen here: https://share.goabstract.com/1d4de827-121c-4179-9e6c-5f45c5c547bb?collectionLayerId=5dc128b4-eba6-4128-8cde-a10f00bff51c&mode=design
